src/Entity/Procost/Projet.php
<?php

namespace App\Entity\Procost;

use App\Repository\Procost\ProjetRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection as Collection;

/**
 * @ORM\Entity(repositoryClass=ProjetRepository::class)
 */
class Projet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_At;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_livraison;

    /**
     * @ORM\OneToMany (targetEntity="App\Entity\Procost\ProjetUser", mappedBy="projet")
     */
    private $projetusers;

    public function __construct()
    {
        $this->created_At=new \DateTime();
        $this->users=new Collection();
        $this->projetusers=new Collection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeInterface $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getDateLivraison(): ?\DateTimeInterface
    {
        return $this->date_livraison;
    }

    public function setDateLivraison(?\DateTimeInterface $date_livraison): self
    {
        $this->date_livraison = $date_livraison;

        return $this;
    }
    /**
     * @return Collection|ProjetUser[]
     */
    public function getProjetUsers():Collection
    {
        return $this->projetusers;
    }
    public function addUser(ProjetUser $projetUser):self
    {
        if(!$this->projetusers->contains($projetUser)){
            $this->projetusers[]=$projetUser;
            $projetUser->setProjet($this);
        }
        return $this;
    }
    public function removeUser(ProjetUser $projetUser):self
    {
        if($this->projetusers->contains($projetUser)){
            $this->projetusers->removeElement($projetUser);
        }
        return $this;
    }


}

src/Entity/Procost/ProjetUser.php
<?php


namespace App\Entity\Procost;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection as Collection;

/**
 * @ORM\Entity(repositoryClass=ProjetUserRepository::class)
 */
class ProjetUser
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\ManyToOne (targetEntity="App\Entity\Procost\Projet", inversedBy="projetusers")
     * @ORM\JoinColumn (nullable=false,name="projet_id")
     */
    private $projet;

    /**
     * @ORM\ManyToOne (targetEntity="App\Entity\User", inversedBy="projetusers")
     * @ORM\JoinColumn (nullable=false,name="user_id")
     */
    private $user;

    /**
     * @ORM\Column(type="float")
     */
    private $cout_ind;

    /**
     * @ORM\Column(type="integer")
     */
    private $temps_ind;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }


    public function getCoutInd()
    {
        return $this->cout_ind;
    }

    public function setCoutInd($cout_ind): self
    {
        $this->cout_ind = $cout_ind;
        return $this;
    }

    public function getTempsInd()
    {
        return $this->temps_ind;
    }

    public function setTempsInd($temps_ind): self
    {
        $this->temps_ind = $temps_ind;
        return $this;
    }

    public function getProjet()
    {
        return $this->projet;
    }

    public function setProjet($projet): self
    {
        $this->projet = $projet;
        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser($user): self
    {
        $this->user = $user;
        return $this;
    }

}

src/Form/ProjetType.php
<?php


use App\Entity\Procost\Projet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('nom',TextType::class,[
                'label'=>'Nom'
            ])
            ->add('description', TextareaType::class,[
                'label'=>'Description'])
            ->add('prix', NumberType::class,[
                'label'=>'Coût horaire']);
    }
    public function configureOptions(OptionsResolver $resolver):void
    {
        $resolver->setDefaults([
            'data_class'=> Projet::class
        ]);
    }
}

src/Controller/ProjetController.php
<?php

namespace App\Controller;

use App\Entity\Procost\Projet;
use App\Repository\Procost\ProjetRepository;
use App\Repository\Procost\ProjetUserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProjetController extends AbstractController
{
    private $em;
    private $projetrepository;
    private $projetuserrepository;

    public function __construct(EntityManagerInterface $em,
                                ProjetRepository $projetRepository,
                                ProjetUserRepository $projetUserRepository)
    {
        $this->em=$em;
        $this->projetrepository=$projetRepository;
        $this->projetuserrepository=$projetUserRepository;
    }

    /**
     * @Route("/projet", name="projet")
     */
    public function index(): Response
    {
        $projets=$this->projetrepository->findAll();
        return $this->render('projet/index.html.twig', [
            'projets' => $projets,
        ]);
    }

    /**
     * @Route("/projet/form/{id?}", name="projet_form")
     */
    public function projetform(Request $request, ?int $id):Response{
        if($id){
            $projet=$this->projetrepository->find($id);
        }
        else{
            $projet=new Projet();
        }
        $form=$this->createForm(\ProjetType::class,$projet);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($projet);
            $this->em->flush();
//            $this->addFlash('success','Merci, votre message a été pris en compte!');
            return $this->redirectToRoute('projet');
        }
        return $this->render('projet/form.html.twig',[
            'form'=>$form->createView()
        ]);
    }

    /**
     * @Route("/projet/detail/{id}", name="projet_detail")
     */
    public function projetdetail(int $id){
        $projettotal=0;
        $projetusers=$this->projetuserrepository->countEmployeursEnProjet($id);
        $projet=$this->projetrepository->find($id);
        $projetsdet=$this->projetuserrepository->findByProjet($id);
        for($i=0;$i<count($projetsdet);$i++){
            $couttotalind=$projetsdet[$i]->getCoutInd()*$projetsdet[$i]->getTempsInd();
            $projettotal+=$couttotalind;
        }
        return $this->render('projet/detail.html.twig',[
            'projet'=>$projet,
            'projetsdet'=>$projetsdet,
            'projettotal'=>$projettotal,
            'projetusers'=>$projetusers
        ]);
    }

    /**
     * @Route("/projet/livre/{id}", name="projet_livre")
     */
    public function livrer(int $id):RedirectResponse{
        $projet=$this->projetrepository->find($id);
        $projet->setDateLivraison(new \DateTime());
        $this->em->persist($projet);
        $this->em->flush();
        return $this->redirectToRoute('projet');
    }
}

templates/projet/detail.html.twig
{% extends 'layout.html.twig' %}
{% block title %}Detail de l'employé{% endblock %}
{% block main_content %}
    <main class="app-content">
        <div class="app-title">
            <div>
                <h1><i class="fa fa-users"></i>&nbsp;projet: {{projet.nom}}</h1>
            </div>
            <ul class="app-breadcrumb breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{path('main')}}"><i class="fa fa-home fa-lg"></i></a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{path('projet')}}">Projets</a>
                </li>
                <li class="breadcrumb-item">Projet:{{projet.nom}}</li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="tile">
                    <table class="table table-striped table-bordered table-sm">
                        <tbody>
                        <tr>
                            <th>Nom</td>
                            <td>{{ projet.nom }}</td>
                        </tr>
                        <tr>
                            <th>Description</td>
                            <td>{{projet.description}}</td>
                        </tr>
                        <tr>
                            <th>Prix</td>
                            <td>{{projet.prix}}</td>
                        </tr>
                        <tr>
                            <th>Date d'initialization</td>
                            <td>{{ projet.createdAt | date('D F Y') }}</td>
                        </tr>
                        <tr>
                            <th>Coût total</td>
                            <td>{{ projettotal }}</td>
                        </tr>
                        <tr>
                            <th>Employeurs en travaillant</td>
                            <td>{{ projetusers }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <a href="{{ path('projet_form',{id:projet.id}) }}" class="btn btn-info">
                        <i class="fa fa-pencil"></i>Modifier
                    </a>
                </div>
            </div>
            <div class="col-md-8">
                <div class="tile pb-5">
                    <h3 class="tile-title">Historique des temps de production</h3>
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-sm">
                            <thead>
                            <tr>
                                <th>Nom du employé</th>
                                <th>Temps</th>
                                <th>Coût total</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for projetdet in projetsdet %}
                                <tr>
                                    <td>{{ projetdet.user.prenom }} {{ projetdet.user.nom|upper }}</td>
                                    <td>{{ projetdet.tempsInd }}</td>
                                    <td>{{projetdet.tempsInd * projetdet.coutInd}}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <hr/>
                    <nav class="float-right">
                        <ul class="pagination">
                            <li class="page-item disabled">
                                <span class="page-link">&laquo;</span>
                            </li>
                            <li class="page-item active" aria-current="page">
                                <span class="page-link">1<span class="sr-only">(current)</span></span>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">2</a></li>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">3</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">&raquo;</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/projet/form.html.twig
{% extends 'layout.html.twig' %}
{% block title %}Projets form{% endblock %}
{% block main_content %}
    <main class="app-content">
        <div class="app-title">
            <div>
                <h1><i class="fa fa-archive"></i>&nbsp;Edition d'un projet</h1>
            </div>
            <ul class="app-breadcrumb breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{path("main")}}"><i class="fa fa-home fa-lg"></i></a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{path('projet')}}">Projets</a>
                </li>
                <li class="breadcrumb-item">Edition d'un projet</li>
            </ul>
        </div>
        <div class="tile">
            {#            <div class="alert alert-dismissible alert-success my-4">#}
            {#                <button class="close" type="button" data-dismiss="alert">×</button><strong>Well done!</strong> Message flash.#}
            {#            </div>#}
            {{ form_start(form,{'attr':{'class':'form-horizontal'}}) }}
            <section>
                <h3>Projet</h3>
                <div class="row mt-4">
                    <div class="offset-md-4 col-md-8">
                        <div class="form-group row">
                            {{ form_errors(form.nom) }}
                            {{ form_label(form.nom) }}
                            <div class="col-md-9">
                                {{ form_widget(form.nom,{
                                    'attr':{
                                        'class':'form_control',
                                        'placeholder':form.nom.vars.label}})
                                }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_errors(form.description) }}
                            {{ form_label(form.description) }}
                            <div class="col-md-9">
                                {{ form_widget(form.description,{
                                    'attr':{
                                        'class':'form_control',
                                        'placeholder':form.description.vars.label}})
                                }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_errors(form.prix) }}
                            {{ form_label(form.prix) }}
                            <div class="col-md-9">
                                {{ form_widget(form.prix,{
                                    'attr':{
                                        'class':'form_control',
                                        'placeholder':form.prix.vars.label}})
                                }}
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div class="row">
                <div class="offset-md-6 col-md-6">
                    <button type="submit" class="btn btn-success"><i class="fa fa-save"></i>Enregistrer</button>
                </div>
            </div>
            {{ form_end(form) }}

        </div>
    </main>
{% endblock %}

templates/projet/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Projet{% endblock %}

{% block main_content %}
    <main class="app-content">
        <div class="app-title">
            <div>
                <h1><i class="fa fa-archive"></i>&nbsp;Projets</h1>
            </div>
            <ul class="app-breadcrumb breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{path("main")}}"><i class="fa fa-home fa-lg"></i></a>
                </li>
                <li class="breadcrumb-item">Projets</li>
            </ul>
        </div>
        <div class="tile pb-5">
            <a href="{{ path('projet_form') }}" class="btn btn-primary float-right mb-4"><i class="fa fa-plus-circle mr-2"></i>Ajouter un projet</a>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Description</th>
                        <th>Prix</th>
                        <th>Date d'initialization</th>
                        <th>action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for projet in projets %}
                        <tr>
                            <td>{{projet.nom}}</td>
                            <td>{{projet.description}}</td>
                            <td>{{projet.prix}}</td>
                            <td>{{projet.createdAt|date('D F Y')}}</td>
                            <td>
                                <a href="{{ path('projet_form',{id:projet.id}) }}" class="btn btn-info btn-sm">
                                    <i class="fa fa-pencil mr-0"></i>
                                </a>
                                <a href="{{ path('projet_detail',{id:projet.id}) }}" class="btn btn-info btn-sm">
                                    <i class="fa fa-eye mr-0"></i>
                                </a>
                                {% if projet.dateLivraison==null %}
                                    <a href="{{ path('projet_livre',{id:projet.id}) }}" class="btn btn-info btn-sm">
                                        <i class="fa fa-check-square mr-0"></i>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <hr/>
            <nav class="float-right">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">&laquo;</span>
                    </li>
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">1<span class="sr-only">(current)</span></span>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">2</a></li>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">3</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">&raquo;</a>
                    </li>
                </ul>
            </nav>
        </div>
    </main>
{% endblock %}