src/Entity/Procost/ProjetUser.php
<?php


namespace App\Entity\Procost;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection as Collection;

/**
 * @ORM\Entity(repositoryClass=ProjetUserRepository::class)
 */
class ProjetUser
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\ManyToOne (targetEntity="App\Entity\Procost\Projet", inversedBy="projetusers")
     * @ORM\JoinColumn (nullable=false,name="projet_id")
     */
    private $projet;

    /**
     * @ORM\ManyToOne (targetEntity="App\Entity\User", inversedBy="projetusers")
     * @ORM\JoinColumn (nullable=false,name="user_id")
     */
    private $user;

    /**
     * @ORM\Column(type="float")
     */
    private $cout_ind;

    /**
     * @ORM\Column(type="integer")
     */
    private $temps_ind;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }


    public function getCoutInd()
    {
        return $this->cout_ind;
    }

    public function setCoutInd($cout_ind): self
    {
        $this->cout_ind = $cout_ind;
        return $this;
    }

    public function getTempsInd()
    {
        return $this->temps_ind;
    }

    public function setTempsInd($temps_ind): self
    {
        $this->temps_ind = $temps_ind;
        return $this;
    }

    public function getProjet()
    {
        return $this->projet;
    }

    public function setProjet($projet): self
    {
        $this->projet = $projet;
        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser($user): self
    {
        $this->user = $user;
        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Procost\ProjetUser;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection as Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;



    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="float")
     */
    private $cout_horaire;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_embauche;
    /**
     * @ORM\ManyToOne (targetEntity="App\Entity\Procost\Metier", inversedBy="users")
     * @ORM\JoinColumn (nullable=false,name="metier_id")
     */
    private $metier;
    /**
     * @ORM\OneToMany (targetEntity="App\Entity\Procost\ProjetUser", mappedBy="user")
     */
    private $projetusers;

    public function __construct()
    {
        $this->projetusers=new Collection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCoutHoraire(): ?float
    {
        return $this->cout_horaire;
    }

    public function setCoutHoraire(float $cout_horaire): self
    {
        $this->cout_horaire = $cout_horaire;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->date_embauche;
    }

    public function setDateEmbauche(\DateTimeInterface $date_embauche): self
    {
        $this->date_embauche = $date_embauche;

        return $this;
    }

    public function getMetier()
    {
        return $this->metier;
    }

    public function setMetier($metier): void
    {
        $this->metier = $metier;
    }
    /**
     * @return Collection|ProjetUser[]
     */
    public function getProjetUsers():Collection
    {
        return $this->projetusers;
    }
    public function addUser(ProjetUser $projetUser):self
    {
        if(!$this->projetusers->contains($projetUser)){
            $this->projetusers[]=$projetUser;
            $projetUser->setUser($this);
        }
        return $this;
    }
    public function removeUser(ProjetUser $projetUser):self
    {
        if($this->projetusers->contains($projetUser)){
            $this->projetusers->removeElement($projetUser);
        }
        return $this;
    }
}

src/Form/EmployeurType.php
<?php


use App\Entity\Procost\Metier;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('prenom', TextType::class,[
            'label'=>'Prénom'
        ])
        ->add('nom',TextType::class,[
            'label'=>'Nom'
        ])
        ->add('email',TextType::class,[
            'label'=>'Email'])
        ->add('metier', EntityType::class,[
            'class'=> Metier::class,
            'choice_label'=>'nom'])
        ->add('cout_horaire', NumberType::class,[
            'label'=>'Coût horaire'])
        ->add('date_embauche', DateType::class,[
            'label'=>'Date d\'embauche']);
    }
    public function configureOptions(OptionsResolver $resolver):void
    {
        $resolver->setDefaults([
            'data_class'=> User::class
        ]);
    }
}

src/Controller/EmployeurController.php
<?php

namespace App\Controller;

use App\Entity\Procost\ProjetUser;
use App\Entity\User;
use App\Repository\Procost\ProjetRepository;
use App\Repository\Procost\ProjetUserRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EmployeurController extends AbstractController
{
    private $userrepository;
    private $projetuserrepository;
    private $em;
    private $projetrepository;
    public function __construct(UserRepository $userRepository,
                                ProjetUserRepository $projetUserRepository,
                                ProjetRepository $projetRepository, EntityManagerInterface $em){
        $this->userrepository=$userRepository;
        $this->projetuserrepository=$projetUserRepository;
        $this->projetrepository=$projetRepository;
        $this->em=$em;
    }
    /**
     * @Route("/employeur", name="employeur")
     */
    public function index(): Response
    {
        $users=$this->userrepository->findAll();
        return $this->render('employeur/index.html.twig', [
            'users' => $users,
        ]);
    }
    /**
     * @Route("/employeur/form/{id?}", name="employeur_form")
     */
    public function employeurform(?int $id,Request $request):Response{
        if($id){
            $user=$this->userrepository->find($id);
        }
        else{
            $user=new User();
        }
        $form=$this->createForm(\EmployeurType::class,$user);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($user);
            $this->em->flush();
//            $this->addFlash('success','Merci, votre message a été pris en compte!');
            return $this->redirectToRoute('employeur');
        }
        return $this->render('employeur/form.html.twig',[
            'form'=>$form->createView()
        ]);
    }
    /**
     * @Route("/employeur/detail/{id?}", name="employeur_detail")
     */
    public function detail(int $id, Request $request):Response{
        $projetuser=new ProjetUser();
        $form=$this->createForm(\ProjetUserType::class,$projetuser);
        $user=$this->userrepository->find($id);
        $projets=$this->projetuserrepository->findByUser($id);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $projetid=$form->get('projet');
            $projet=$this->projetrepository->find($projetid);
            $projet->addUser($projetuser);
            $user->addUser($projetuser);
            $this->em->persist($projetuser);
            $this->em->flush();
//            $this->addFlash('success','Merci, votre message a été pris en compte!');
            return $this->redirectToRoute('employeur');
        }
        return $this->render('employeur/detail.html.twig',[
            'user'=>$user,
            'projets'=>$projets,
            'form'=>$form->createView()
        ]);
    }
}

templates/employeur/detail.html.twig
{% extends 'layout.html.twig' %}
{% block title %}Detail de l'employé{% endblock %}
{% block main_content %}
    <main class="app-content">
        <div class="app-title">
            <div>
                <h1><i class="fa fa-users"></i>&nbsp;Suivi de {{user.prenom}} {{ user.nom|upper }}</h1>
            </div>
            <ul class="app-breadcrumb breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{path('main')}}"><i class="fa fa-home fa-lg"></i></a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{path('employeur')}}">Employés</a>
                </li>
                <li class="breadcrumb-item">Suivi de {{user.prenom}} {{ user.nom|upper }}</li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="tile">
                    <table class="table table-striped table-bordered table-sm">
                        <tbody>
                        <tr>
                            <th>Prénom</td>
                            <td>{{ user.prenom }}</td>
                        </tr>
                        <tr>
                            <th>Nom</td>
                            <td>{{ user.nom|upper }}</td>
                        </tr>
                        <tr>
                            <th>Email</td>
                            <td>{{user.email}}</td>
                        </tr>
                        <tr>
                            <th>Métier</td>
                            <td>{{ user.metier.nom }}</td>
                        </tr>
                        <tr>
                            <th>Coût horaire</td>
                            <td>{{ user.coutHoraire }}</td>
                        </tr>
                        <tr>
                            <th>Date d'embauche</td>
                            <td>{{ user.dateEmbauche|date('D M Y') }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <a href="{{ path('employeur_form',{id:user.id}) }}" class="btn btn-info">
                        <i class="fa fa-pencil"></i>Modifier
                    </a>
                </div>
                <div class="tile">
                    {{ form_start(form) }}
                    <h3 class="title-title mb-4">Ajouter un temps</h3>


                        <div class="form-group row">
                            {{ form_errors(form.projet) }}
                            {{ form_label(form.projet) }}
                            <div class="col-md-6">
                                {{ form_widget(form.projet,{
                                    'attr':{
                                        'class':'form_control'}})
                                }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_errors(form.temps_ind) }}
                            {{ form_label(form.temps_ind) }}
                            <div class="col-md-6">
                                {{ form_widget(form.temps_ind,{
                                    'attr':{
                                        'class':'form_control'}})
                                }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="offset-md-6 col-md-8">
                                <button type="submit" class="btn btn-success"><i class="fa fa-save"></i>Enregistrer</a>
                            </div>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
            <div class="col-md-8">
                <div class="tile pb-5">
                    <h3 class="tile-title">Historique des temps de production</h3>
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-sm">
                            <thead>
                            <tr>
                                <th>Projet</th>
                                <th>Temps</th>
                                <th>Date de saisie</th>
                                <th>Coût total</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for projetind in projets %}
                                <tr>
                                    <td>{{ projetind.projet.nom }}</td>
                                    <td>{{ projetind.tempsInd }}</td>
                                    <td>23-04-2018</td>
                                    <td>{{projetind.tempsInd * projetind.coutInd}}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <hr/>
                    <nav class="float-right">
                        <ul class="pagination">
                            <li class="page-item disabled">
                                <span class="page-link">&laquo;</span>
                            </li>
                            <li class="page-item active" aria-current="page">
                                <span class="page-link">1<span class="sr-only">(current)</span></span>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">2</a></li>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">3</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">&raquo;</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/employeur/form.html.twig
{% extends 'layout.html.twig' %}
{% block title %}Employeurs form{% endblock %}
{% block main_content %}
    <main class="app-content">
        <div class="app-title">
            <div>
                <h1><i class="fa fa-user"></i>&nbsp;Edition d'un employé</h1>
            </div>
            <ul class="app-breadcrumb breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{path("main")}}"><i class="fa fa-home fa-lg"></i></a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{path('employeur')}}">Employeurs</a>
                </li>
                <li class="breadcrumb-item">Edition d'un employé</li>
            </ul>
        </div>
        <div class="tile">
            {#            <div class="alert alert-dismissible alert-success my-4">#}
            {#                <button class="close" type="button" data-dismiss="alert">×</button><strong>Well done!</strong> Message flash.#}
            {#            </div>#}
            {{ form_start(form,{'attr':{'class':'form-horizontal'}}) }}
            <section>
                <h3>Informations générales</h3>
                <div class="row mt-4">
                    <div class="offset-md-4 col-md-8">
                        <div class="form-group row">
                            {{ form_errors(form.prenom) }}
                            {{ form_label(form.prenom) }}
                            <div class="col-md-9">
                                {{ form_widget(form.prenom,{
                                    'attr':{
                                        'class':'form_control',
                                        'placeholder':form.prenom.vars.label}})
                                }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_errors(form.nom) }}
                            {{ form_label(form.nom) }}
                            <div class="col-md-9">
                                {{ form_widget(form.nom,{
                                    'attr':{
                                        'class':'form_control',
                                        'placeholder':form.nom.vars.label}})
                                }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_errors(form.email) }}
                            {{ form_label(form.email) }}
                            <div class="col-md-9">
                                {{ form_widget(form.email,{
                                    'attr':{
                                        'class':'form_control',
                                        'placeholder':form.email.vars.label}})
                                }}
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <hr/>
            <section>
                <h3>Production</h3>
                <div class="row mt-4">
                    <div class="offset-md-4 col-md-8">
                        <div class="form-group row">
                            {{ form_errors(form.metier) }}
                            {{ form_label(form.metier) }}
                            <div class="col-md-9">
                                {{ form_widget(form.metier,{
                                    'attr':{
                                        'class':'form_control',
                                        }})
                                }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_errors(form.cout_horaire) }}
                            {{ form_label(form.cout_horaire) }}
                            <div class="col-md-9">
                                {{ form_widget(form.cout_horaire,{
                                    'attr':{
                                        'class':'form_control',
                                        'placeholder':form.cout_horaire.vars.label}})
                                }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_errors(form.date_embauche) }}
                            {{ form_label(form.date_embauche) }}
                            <div class="col-md-9">
                                {{ form_widget(form.date_embauche,{
                                    'attr':{
                                        'class':'form_control',
                                        'placeholder':form.date_embauche.vars.label}})
                                }}
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div class="row">
                <div class="offset-md-6 col-md-6">
                    <button type="submit" class="btn btn-success"><i class="fa fa-save"></i>Enregistrer</button>
                </div>
            </div>
            {{ form_end(form) }}

        </div>
    </main>
{% endblock %}

templates/employeur/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Employeurs{% endblock %}

{% block main_content %}
    <main class="app-content">
        <div class="app-title">
            <div>
                <h1><i class="fa fa-user"></i>&nbsp;Employeurs</h1>
            </div>
            <ul class="app-breadcrumb breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{path("main")}}"><i class="fa fa-home fa-lg"></i></a>
                </li>
                <li class="breadcrumb-item">Employeurs</li>
            </ul>
        </div>
        <div class="tile pb-5">
            <a href="{{ path('employeur_form') }}" class="btn btn-primary float-right mb-4"><i class="fa fa-plus-circle mr-2"></i>Ajouter un employeur</a>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Email</th>
                        <th>Métier</th>
                        <th>Coût horaire</th>
                        <th>Date d'embauche</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{user.prenom}} {{ user.nom|upper }}</td>
                            <td>{{user.email}}</td>
                            <td>{{user.metier.nom}}</td>
                            <td>{{user.coutHoraire}} €</td>
                            <td>{{user.dateEmbauche | date("F Y")}}</td>
                            <td>
                                <a href="{{ path('employeur_detail',{id:user.id}) }}" class="btn btn-primary btn-sm">
                                    <i class="fa fa-eye mr-0"></i>
                                </a>
                                <a href="{{ path('employeur_form',{id:user.id}) }}" class="btn btn-info btn-sm">
                                    <i class="fa fa-pencil mr-0"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <hr/>
            <nav class="float-right">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">&laquo;</span>
                    </li>
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">1<span class="sr-only">(current)</span></span>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">2</a></li>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">3</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">&raquo;</a>
                    </li>
                </ul>
            </nav>
        </div>
    </main>
{% endblock %}